ext4: set s_op before initializing multi-block allocator
Otherwise strange things will happends, because of standard
s_op->alloc_inode, that don't do ext4 specific stuff.

In my case deadlock happends, because of:
Breakpoint 1, ext4_evict_inode (inode=0xffff88007bbd4b18) at inode.c:183
183     {
3: inode->i_ino = 1
2: ((struct ext4_inode_info *)((char *)inode - 0xb0))->i_ino = <error: There is no member named i_ino.>
1: ((struct ext4_inode_info *)((char *)inode - 0xb0))->i_ioend_count = {
  counter = 1 # MUST BE ZERO
}